###
http://localhost:9090/api/istio/rbac?Version=2020-04-10&Action=EnableServiceAuth

###

POST http://localhost:9090/api/istio/rbac/v2?Version=2020-04-10&Action=UpdateServiceAuthRule
Content-Type: application/json

{
  "Service": "sleep3.rbac-test-system",
  "AuthRules": [
    {
      "RuleName": "test1",
      "MatchType": "service",
      "MatchApis": "*:/anything/api1;*:/anything/api2;*:/anything/api3;",
      "MatchConditions": "sleep1.rbac-test-system"
    }
  ]
}